Message Wall Updates (Pinned Messages Location/Display, Filtering Messages Displayed Based on Role)
lablueprint/friends-of-the-children pull request #22
Opened 2023-01-19 06:54 UTC by erinkwon01

1. Pinned messages should be displayed at the top, and it looks light red with the pinned button yellow.
2. Mentors can only see messages targeted for mentors and corresponding service area, caregivers can only see messages targeted for caregivers and corresponding service area. Admin can see all messages. 
3. Admin is the only one able to submit messages.

* Issues for the future:
* When you pin messages, it slightly glitches (especially noticeable when pinning top message).

<img width="1439" alt="Screen Shot 2023-01-18 at 10 53 27 PM" src="https://user-images.githubusercontent.com/52299644/213375265-c2aa3afb-84d8-45e4-9417-71a7db2391ea.png">
This is when Bob (profile) is "Caregiver" in service area "ms."

2023-01-26 06:19 UTC, xu-jerry requested changes

2023-01-26 06:19 UTC, xu-jerry commented on src/pages/MessageWall.jsx
> +      messages.filter((message) => (message.pinned === true && message.serviceArea[0] === serviceArea.toLowerCase() && (message.target[0] === role.toLowerCase() || (message.target.length > 1 && messa
I would probably change this to service area is in the service area array, instead of checking the first one. Similar with target.

2023-01-28 20:11 UTC, erinkwon01 commented
@xu-jerry Just made the edits! I had to git pull before making changes because of a warning, and I don't think that would have caused any issues :O

2023-01-28 21:15 UTC, xu-jerry approved these changes
Looks good!! :D ty for making the changes!

2023-01-28 21:15 UTC, merged