Requests
lablueprint/friends-of-the-children pull request #50
Opened 2023-04-13 06:11 UTC by galenheuer

created a table to show requests for admin to approve, working on implementing checkboxes

2023-05-18 04:03 UTC, erinkwon01 commented on client/src/components/AdminTable.jsx
> +  // setTable(rows);
Lines 37, 38 are those comments necessary?

2023-05-18 04:06 UTC, danielkao14 requested changes
A slight bug:
- pressing delete doesn't refresh the page automatically (functionality seems to work)

2023-05-18 04:10 UTC, erinkwon01 reviewed
Heyy great job overall, this feature is super rad! The error that I found was that, the waiting message _does_ indeed show after I sign up for a new account, BUT I can immediately log in after going back to the Login page. I think the error I got as about updateAppProfile being undefined!

2023-05-18 04:10 UTC, erinkwon01 commented on client/src/components/AdminTable.jsx
> +  // }, [rows]);
Are these comments necessary?

2023-05-18 04:10 UTC, erinkwon01 commented on client/src/components/AdminTable.jsx
> +        // setTimeout(() => { window.location.reload(); }, 800);
Is this comment necessary?

2023-05-18 04:10 UTC, erinkwon01 commented on client/src/components/AdminTable.jsx
> +  // useEffect(() => console.log(table), [table]);
Is this comment necessary?

2023-05-18 04:10 UTC, erinkwon01 commented on client/src/components/AdminTable.jsx
> +      // console.log(prevValue.checked);
I think you can remove this!

2023-05-18 04:10 UTC, erinkwon01 commented on client/src/pages/Requests.jsx
> +      // ask jerry how to get the data sorted
Can this comment be deleted?

2023-05-18 04:10 UTC, erinkwon01 commented on client/src/pages/Requests.jsx
> +      {/* <button type="button">Submit</button> */}
Can this comment be deleted?

2023-05-18 04:10 UTC, erinkwon01 commented on client/src/pages/Requests.jsx
> +      {/* <p>{numApproved}</p> */}
Can this comment be deleted?

2023-05-18 04:10 UTC, erinkwon01 commented on client/src/pages/UserNotApproved.jsx
> +/* eslint-disable no-unused-vars */
Can you delete this comment?

2023-05-22 17:01 UTC, xu-jerry approved these changes
Looks good!

2023-05-22 17:02 UTC, merged